# Generated by Django 3.0.5 on 2022-02-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20220211_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
