# Generated by Django 3.0.5 on 2022-02-12 03:15

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20220211_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(upload_to=feed.models.get_path),
        ),
    ]
